"""Initial revision

Revision ID: 6958eff3e4c4
Revises: 74c9c33168fb
Create Date: 2024-10-11 19:57:01.925146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6958eff3e4c4'
down_revision: Union[str, None] = '74c9c33168fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_services', sa.Column('application_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'application_services', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_services', type_='foreignkey')
    op.drop_column('application_services', 'application_id')
    # ### end Alembic commands ###
