"""Initial revision

Revision ID: 74c9c33168fb
Revises: 3fba713fb782
Create Date: 2024-10-09 21:00:28.425838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c9c33168fb'
down_revision: Union[str, None] = '3fba713fb782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('company_name', sa.String(), nullable=False))
    op.add_column('applications', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('applications', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('company_name', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'username')
    op.drop_column('applications', 'email')
    op.drop_column('applications', 'phone_number')
    op.drop_column('applications', 'company_name')
    # ### end Alembic commands ###
