"""Поле Статус в модели Application

Revision ID: b3cd4432c5b1
Revises: 6958eff3e4c4
Create Date: 2024-10-12 17:17:00.860087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cd4432c5b1'
down_revision: Union[str, None] = '6958eff3e4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'application_services', 'applications', ['application_id'], ['id'])
    op.add_column('applications', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'status')
    op.drop_constraint(None, 'application_services', type_='foreignkey')
    # ### end Alembic commands ###
